name: CI - Vite React Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Remplacez par la version souhaitée

      # Changez de répertoire vers 'react' avant d'installer les dépendances
      - name: Install dependencies
        run: |
          cd react
          npm install

      # Exécutez les tests si vous en avez
      - name: Run tests
        run: |
          cd react
          npm run test

      # Construisez votre projet
      - name: Build project
        run: |
          cd react
          npm run build
