name: CI - Vite React Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Remplacez par la version souhaitée

      - name: Install dependencies
        run: npm install  # Assurez-vous que le fichier package.json est présent

      - name: Run tests
        run: npm run test  # Si vous avez des tests configurés

      - name: Build project
        run: npm run build  # Cela construira votre projet
